### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by shahrozekhan** [icerockdev/moko-resources#607]
org.gradle.configurationcache.ConfigurationCacheError: Configuration cache state could not be cached: field `apiConfiguration` of `org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.DefaultKotlinCompilationConfigurationsContainer` bean found in field `dependencyConfigurations` of `org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.KotlinCompilationImpl$Params` bean found in field `params` of `org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.KotlinCompilationImpl` bean found in field `$$delegate_0` of `org.jetbrains.kotlin.gradle.plugin.mpp.KotlinCommonCompilation` bean found in field `underlying` of `org.jetbrains.kotlin.gradle.utils.MutableObservableSetImpl` bean found in field `compilations` of `org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSet` bean found in field `$kotlinSourceSet` of `dev.icerock.gradle.MultiplatformResourcesPlugin$createSourceSet$1` bean found in field `sourceSet` of `dev.icerock.gradle.generator.common.CommonMRGenerator` bean found in field `generator` of task `:shared:generateMRcommonMain` of type `dev.icerock.gradle.tasks.GenerateMultiplatformResourcesTask`: error writing value of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration'
	at org.gradle.configurationcache.problems.ProblemsListener$DefaultImpls.onError(ProblemsListener.kt:37)
	at org.gradle.configurationcache.problems.ConfigurationCacheProblems.onError(ConfigurationCacheProblems.kt:38)
	at org.gradle.configurationcache.serialization.AbstractIsolateContext.onError(Contexts.kt:418)
	at org.gradle.configurationcache.serialization.beans.BeanPropertyWriterKt.writeNextProperty(BeanPropertyWriter.kt:100)
	at org.gradle.configurationcache.serialization.beans.BeanPropertyWriter.writeStateOf(BeanPropertyWriter.kt:53)
	at org.gradle.configurationcache.serialization.codecs.BeanCodec.writeBeanOf(BeanCodec.kt:59)
	at org.gradle.configurationcache.serialization.codecs.BeanCodec.encode(BeanCodec.kt:37)
	at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$encodeLoop$1.invokeSuspend(Combinators.kt:144)

**Comment by ismai117** [comment]
did you find a solution for this? im having the same problem

**Comment by shahrozekhan** [comment]
> did you find a solution for this? im having the same problem

I am looking into the solution. Try to migrate your studio version to hedgehog.

**Comment by deBasMan21** [comment]
Im still having this issue and i am on the latest version of android studio (hedgehog). Does anyone have any tips on how to solve this?

**Comment by shahrozekhan** [comment]
I have started using jet brain compose latest release... 1.6.0 nd above. U
can use dev version as well..

**Comment by Manriif** [comment]
Tried 0.24.0-beta-1 and this issue seems to have been fixed. 
Gradle configuration-cache makes builds incredibly faster.
